### PR TITLE
Add function to check if any virtual environment is active

### PR DESCRIPTION
**Pull request by ryandward**
Added function to check if other common environment managers are active before attempting to activate.

### CODE REVIEW

**Comment by ryandward** [comment]
I'm not sure what's going on with the tests here, but I don't think these were things that I changed.

**Comment by nicopauss** [comment]
Hello,

First, thank you for your interest in the project.

This project has not seen some changes in a while, and the environment tests are indeed broken. It still uses Azure tests with outdated and removed VM images.
I will need to migrate them to Github action. I will try to fix them ASAP.

However, concerning your pull request, I don't quite understand your use-case here.
To me, `pyvenv-activate` has two modes:
 1. Manually through `pyvenv_activate()` and `pyvenv_deactivate()` functions.
  => In that case, I don't quite understand why you would try to call `pyvenv_activate()` on an already activated environment. If this is what you want to avoid, I suggest that you do a wrapper above `pyvenv_activate()` instead of trying to fix it directly in this project.

 2. Automatically with `pyvenv_auto_activate`
  => In that case, this should already be covered. If this is not the case for you, this is a bug and please open an issue. But your commit is not the correct way of fixing this issue.

Can you elaborate on what is your use-case?

Note that Conda environments are not supposed to be supported.

**Comment by ryandward** [comment]
Yeah, my use case is loading this as an extension in my .zshrc, using omz.

> Automatically with `pyvenv_auto_activate`
> => In that case, this should already be covered. If this is not the case for you, this is a bug and please open an issue. But your commit is not the correct way of fixing this issue.

```
plugins=(git zsh-autosuggestions zsh-autocomplete fast-syntax-highlighting web-search pyenv pyvenv-activate autojump)
```

I've actually never seen it function as intended, in that case. `pyvenv_auto_activate` has always successfully activated on top of whatever other environment I am currently using.

**Comment by ryandward** [comment]
I don't mind creating an issue, but I figured a similar fix could be useful for whoever else might be using `pyvenv_auto_activate`. Even in VSCode, where I am using a variety of different environments, you can hopefully see that the check is now preventing the activation.

Screenshot from 2024-02-08 02-23-33

**Comment by nicopauss** [comment]
So I have managed to reproduce your issue:

```
pauss@iltp-042: ~/tmp$ tree -a -I 'lib' test-multiple-venv-autoactivate
test-multiple-venv-autoactivate
├── .pyvenv_venv_path
├── root_venv
│   └ ...
└── sublvl1
    ├── .pyvenv_venv_path
    └── sublvl1_venv
        └ ...

12 directories, 24 files
pauss@iltp-042: ~/tmp$ echo $VIRTUAL_ENV

pauss@iltp-042: ~/tmp$ cd test-multiple-venv-autoactivate/
(root_venv) pauss@iltp-042: ~/tmp/test-multiple-venv-autoactivate$ echo $VIRTUAL_ENV
/home/pauss/tmp/test-multiple-venv-autoactivate/root_venv
(root_venv) pauss@iltp-042: ~/tmp/test-multiple-venv-autoactivate$ cat .pyvenv_venv_path
/home/pauss/tmp/test-multiple-venv-autoactivate/root_venv
(root_venv) pauss@iltp-042: ~/tmp/test-multiple-venv-autoactivate$ cd sublvl1/
(sublvl1_venv) pauss@iltp-042: ~/tmp/test-multiple-venv-autoactivate/sublvl1$ echo $VIRTUAL_ENV
/home/pauss/tmp/test-multiple-venv-autoactivate/sublvl1/sublvl1_venv
(sublvl1_venv) pauss@iltp-042: ~/tmp/test-multiple-venv-autoactivate/sublvl1$ cat .pyvenv_venv_path
/home/pauss/tmp/test-multiple-venv-autoactivate/sublvl1/sublvl1_venv
```

But I don't actually think your behaviour is what we actually want.
IMO, we should always activate the lowest virtual environment available by default. This is because the lowest environment should have the correct environment for the current project.
Note that we don't active multiple environment at once.
In my example, `root_venv` is deactivated when I enter `sublvl1` before activating `sublvl1_venv`.

What we can do, is to add an option to change this behaviour, and keep the top level environment.
But by default, IMO we should keep the current behaviour.

**Comment by ryandward** [comment]
An optional setting would be helpful. I should be more specific, my use case often involves grabbing a many different modules in a `pipenv` for development, then creating a more carefully curated `mamba` environment for more reproducible environments once the code settles down a bit. So, in the same directory I am often switching between the two.

**Comment by nicopauss** [comment]
Alright then, let's do this.
I am adding a feature request to add an option to change this behaviour.

I am closing this pull request and will add this new feature when I have time to work on `pyvenv-activate`.

**Comment by ryandward** [comment]
I really appreciate it

**Comment by nicopauss** [comment]
Sorry, but I will not have time to work on pyvenv_activate this week.
I have this item in my TODO list, and will work on it as soon as I have some time available for it.

**Comment by nicopauss** [comment]
Can you look at the branch [np-4-option-keep-top-env](https://github.com/Intersec/pyvenv-activate/tree/np-4-option-keep-top-env) and the option `PYVENV_ACTIVATE_TOP_LEVEL_ENV` if this is what you wanted?

**Comment by ryandward** [comment]
Thanks for introducing `PYVENV_ACTIVATE_TOP_LEVEL_ENV=1` in the branch `np-4-option-keep-top-env` as a response to the concerns raised. However, after testing, I'm still facing the issue where `pyvenv-activate` overrides the `which python` command inappropriately, particularly when integrated with conda or mamba environments. I've attached a screenshot to illustrate the specific problem that persists.

My main hope was to find a solution where the activation process could be more selective.

I appreciate your efforts to engage with the feedback.

image

I'll just attach a screenshot from the hacks I madde, which seem to work for my purposes -- at least. Hopefully it's clear that the activator is using some restraint here.

image

Upon further reflection, I realize this might be a rather unique scenario -- to be using multiple environment managers for the same project.

**Comment by nicopauss** [comment]
Just a small observation.
If you activate your mamba environment manually, why keep using the auto-active functionality?

You can disable it manually for the current shell session with `pyvenv_auto_activate_disable` you want you want to still use globally in other cases.

**Comment by ryandward** [comment]
The real issue isn't actually even when I'm manually activating a different environment manager, it's especially problematic in VS Code -- where it also tries to respect the environment. However, when you open the terminal from VS Code, the activator activates on top of the existing environment. 

Nevertheless, I only use mamba for academic code publishing, and pipenv for everything else (95+% of the time), including academic code development for the same projects. So it's easy to forget the activator is doing its thing because it just becomes expected behavior.

**Pull request closed without merging**
